"""Phase 3d: SHAP explanations and error analysis for the final model.

Global SHAP importance uses the training split. Per-patient explanations and the test
error list use the held-out test predictions already produced by 05_final_test.py; no
decision is changed based on them.
"""

from __future__ import annotations

import joblib
import numpy as np
import pandas as pd

from oncolens import config
from oncolens.data import load_splits, split_features_target
from oncolens.errors import (
    borderline_share,
    label_outcomes,
    misclassified_table,
    outcome_profile,
    relative_position,
    standardized_profile,
)
from oncolens.explain import build_explainer, explain_rows, global_importance, top_contributions
from oncolens.io_utils import dataframe_to_markdown, read_json, write_json

N_PROFILE_FEATURES: int = 8


def pick_example_patients(outcome: pd.Series, proba: np.ndarray) -> dict[str, int]:
    """Choose test rows to explain: every FN, the highest-probability FP, and confident TP/TN."""
    picks: dict[str, int] = {}
    fn_rows = np.flatnonzero(outcome == "FN")
    for i, row in enumerate(fn_rows):
        picks[f"missed_malignant_{i + 1}"] = int(row)
    fp_rows = np.flatnonzero(outcome == "FP")
    if len(fp_rows):
        picks["false_alarm_highest_p"] = int(fp_rows[np.argmax(proba[fp_rows])])
    tp_rows = np.flatnonzero(outcome == "TP")
    picks["confident_malignant"] = int(tp_rows[np.argmax(proba[tp_rows])])
    tn_rows = np.flatnonzero(outcome == "TN")
    picks["confident_benign"] = int(tn_rows[np.argmin(proba[tn_rows])])
    return picks


def describe_errors(profile_raw: pd.DataFrame, position: pd.DataFrame, oof_errors: pd.DataFrame,
                    test_errors: pd.DataFrame, threshold: float) -> str:
    """Write a short Markdown report whose numbers all come from the tables passed in."""
    counts = oof_errors["outcome"].value_counts()
    share = borderline_share(oof_errors)
    lines = [
        "# Error analysis (generated by scripts/06_explain_errors.py)",
        "",
        f"Decision threshold: p(malignant) >= {threshold}.",
        "",
        f"* Training split, out-of-fold: {counts.get('FN', 0)} missed malignant (FN), "
        f"{counts.get('FP', 0)} false alarms (FP).",
        f"* Held-out test split: {int((test_errors['outcome'] == 'FN').sum())} FN, "
        f"{int((test_errors['outcome'] == 'FP').sum())} FP.",
        f"* {share:.0%} of out-of-fold errors had a predicted probability within 0.15 of the threshold "
        f"(median distance {oof_errors['distance_to_threshold'].median():.3f}).",
        "",
        "## Mean feature values by outcome (training split, out-of-fold, top SHAP features)",
        "",
        dataframe_to_markdown(profile_raw.round(4), "feature"),
        "",
        "## Relative position of each error group (0 = average TN, 1 = average TP)",
        "",
        dataframe_to_markdown(position.round(2), "feature"),
        "",
    ]
    for group, label in (("FN", "Missed malignant tumors (FN)"), ("FP", "False alarms (FP)")):
        if group in position:
            lines.append(f"* {label}: median relative position {position[group].median():.2f} across these "
                         f"{len(position)} features.")
    medians = position.median()
    in_overlap = bool(((medians > 0) & (medians < 1)).all())
    lines += ["", "## Reading the numbers", ""]
    if in_overlap:
        lines.append("* Both error groups have a median position strictly between 0 and 1: on most of the top "
                     "features they sit in the overlap between the class averages, not deep inside the "
                     "wrong class.")
    size_cols = [f for f in ("worst radius", "worst area") if f in profile_raw.index]
    for f in size_cols:
        lines.append(f"* {f}: TN {profile_raw.loc[f, 'TN']:.4g}, FP {profile_raw.loc[f, 'FP']:.4g}, "
                     f"FN {profile_raw.loc[f, 'FN']:.4g}, TP {profile_raw.loc[f, 'TP']:.4g}.")
    r = profile_raw.loc[size_cols]
    if size_cols and (r["FP"] > r["TN"]).all() and (r["FN"] < r["TP"]).all():
        lines.append("* On these size features, false alarms are larger than typical benign tumors and missed "
                     "cancers are smaller than typical malignant ones.")
    lines += [
        f"* Caveat: there are only {counts.get('FN', 0)} out-of-fold FN, so FN averages are noisy "
        "(a single unusual sample can move them a lot, including outside the 0-1 range).",
        "* See figures/15_error_profile.png for the same comparison as a chart.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    """Compute SHAP values, pick example patients, and analyse misclassifications."""
    train, test = load_splits()
    X, y = split_features_target(train)
    X_test, y_test = split_features_target(test)
    chosen = read_json(config.RESULTS_DIR / "model_selection.json")["chosen_model"]
    threshold = read_json(config.RESULTS_DIR / "threshold_selection.json")["chosen_threshold"]
    pipeline = joblib.load(config.FINAL_MODEL_FILE)

    pe = build_explainer(pipeline, X)
    train_expl = explain_rows(pe, X)
    importance = global_importance(train_expl)
    importance.round(5).to_csv(config.RESULTS_DIR / "shap_global_importance.csv", index=False)

    test_proba = pd.read_csv(config.RESULTS_DIR / "test_probabilities.csv")[chosen].to_numpy()
    test_outcome = label_outcomes(y_test, test_proba, threshold)
    test_expl = explain_rows(pe, X_test)
    picks = pick_example_patients(test_outcome, test_proba)
    rows = []
    for tag, r in picks.items():
        contrib = top_contributions(test_expl, r, k=5)
        rows.append({"example": tag, "test_row": r, "true_label": int(y_test.iloc[r]),
                     "outcome": test_outcome.iloc[r], "p_malignant": round(float(test_proba[r]), 4),
                     "top_features": "; ".join(f"{f} ({s:+.2f})" for f, s in zip(contrib.feature, contrib.shap))})
    pd.DataFrame(rows).to_csv(config.RESULTS_DIR / "shap_example_patients.csv", index=False)

    oof_proba = pd.read_csv(config.RESULTS_DIR / "oof_probabilities_train.csv")[chosen].to_numpy()
    oof_outcome = label_outcomes(y, oof_proba, threshold)
    oof_errors = misclassified_table(X, y, oof_proba, threshold, "train_oof")
    test_errors = misclassified_table(X_test, y_test, test_proba, threshold, "test")
    pd.concat([oof_errors, test_errors]).round(4).to_csv(config.RESULTS_DIR / "misclassified_samples.csv",
                                                         index=False)

    features = importance["feature"].head(N_PROFILE_FEATURES).tolist()
    profile_raw = outcome_profile(X, oof_outcome, features)
    profile_z = standardized_profile(X, oof_outcome, features)
    profile_raw.round(4).to_csv(config.RESULTS_DIR / "error_profile_raw.csv", index_label="feature")
    profile_z.round(4).to_csv(config.RESULTS_DIR / "error_profile_zscore.csv", index_label="feature")
    position = relative_position(profile_raw)
    position.round(4).to_csv(config.RESULTS_DIR / "error_relative_position.csv", index_label="feature")

    write_json(
        {
            "threshold": threshold,
            "oof_outcome_counts": oof_outcome.value_counts().to_dict(),
            "test_outcome_counts": test_outcome.value_counts().to_dict(),
            "oof_errors_borderline_share_within_0.15": borderline_share(oof_errors),
            "oof_errors_median_distance_to_threshold": float(oof_errors["distance_to_threshold"].median()),
            "median_relative_position": position.median().round(4).to_dict(),
            "profile_features": features,
            "example_patients": picks,
        },
        config.RESULTS_DIR / "error_analysis.json",
    )
    (config.RESULTS_DIR / "error_analysis.md").write_text(
        describe_errors(profile_raw, position, oof_errors, test_errors, threshold), encoding="utf-8"
    )
    print(f"SHAP top features: {features[:5]}; OOF errors: {len(oof_errors)}, test errors: {len(test_errors)}")


if __name__ == "__main__":
    main()
